name: Deployment stage
on:
  repository_dispatch:
    types: [app_delivery]
env:
  APP_NAME: ${{ github.event.client_payload.app_name }}
  APP_VERSION: ${{ github.event.client_payload.app_version }}
  APP_AUTHOR: ${{ github.event.client_payload.app_author }}
jobs:
  read-payload:
    name: Reads payload
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Reads payload fields
        run: |
          echo 'App name is: ${{ env.APP_NAME }}'
          echo 'App version is: ${{ env.APP_VERSION }}'
          echo 'App author is: ${{ env.APP_AUTHOR }}'
          date >> audit.log
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update audit data'
          branch: master